#!/bin/bash

JOB_NAME=$1
EXPERIENCE_NAME=$2
CPLEX_PATH=$3

# export PATH="$CPLEX_PATH:$PATH"
export PATH="/opt/cplex/$CPLEX_PATH:$PATH"

echo "$JOB_NAME $EXPERIENCE_NAME $CPLEX_PATH"

python $JOB_NAME
